version: '2'
services:

  robot-framework:
    build:
      context: ./docker/robot-javafx-demo
    ports:
      - '80:80'
    volumes:
      - './src/test/robotframework/:/robot'
      - screen-thing:/tmp/.X11-unix
      - javafxbinaryshare:/javafxbinary
    networks:
      - testapp
    environment:
      - RESOLUTION=1920x1080
      - X11VNC_ARGS=-multiptr

  javafxcompile:
    build:
      context: ./
      dockerfile: Dockerfile_build
    restart: on-failure
    networks:
      - testapp
    volumes:
      - './src/test/robotframework/:/robot' # Required for executing tests from robot-framework container
      - screen-thing:/tmp/.X11-unix
      - javafxbinaryshare:/javafxbinary
    environment:
      - DISPLAY=:1

#  javafxrelease:
#    build:
#      context: ./
#      dockerfile: Dockerfile_release
#    restart: on-failure
#    networks:
#      testapp:
#        aliases:
#         - javafxcompile
#    volumes:
#      - './src/:/src' # ScreenCapturingTest.robot require this.
#      - screen-thing:/tmp/.X11-unix
#    environment:
#      - DISPLAY=:20.0

networks:
  testapp:
volumes:
  screen-thing:
  javafxbinaryshare:
