name: Java CI

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # Disabled before JKD 11 support 
    # https://bugs.launchpad.net/ubuntu/+source/openjfx/+bug/1825054
    #- name: Set up JDK 1.8
    #  uses: actions/setup-java@v1
    #  with:
    #    java-version: 11
    #    java-package: jdk+fx
    - name: Install JDK
      run: sudo apt-get update && sudo apt install openjdk-8-jdk openjfx=8u161-b12-1ubuntu2 libopenjfx-java=8u161-b12-1ubuntu2 libopenjfx-jni=8u161-b12-1ubuntu2
    - name: Set Default java
      run: sudo update-java-alternatives -s /usr/lib/jvm/java-1.8.0-openjdk-amd64
    - name: Install virtual display and window manager
      run: sudo apt-get install xvfb metacity
    - name: Run tests in virtual display with window manager
      run: xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" --server-num=1 sh -c 'metacity --replace --display $DISPLAY & mvn -B verify'
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: robot-results-linux
        path: target/robotframework-reports/

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk+fx
    - name: Run tests
      run: mvn -B verify
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: robot-results-windows
        path: target/robotframework-reports/
